### ISSUE TITLE
Suggested setting for LSPosed

### ISSUE THREAD

**Issue by srccrow** [TacoTheDank/Scoop#3]
Hello, I would like to ask if there is a necessary setting to select for LSPosed.

**Comment by TacoTheDank** [comment]
Nope, currently there is not :( It only supports the original Xposed.

I don't think the app actually does any hooking anymore, so I might remove Xposed support altogether.

**Comment by srccrow** [comment]
This what I see:

```021-04-07 17:23:36.036 E/taco.scoop(11332-11332): java.lang.NoSuchMethodError: tk.wasdennnoch.scoop.ScoopApplication#xposedActive()#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at tk.wasdennnoch.scoop.XposedHook.handleLoadPackage(XposedHook.java:97)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at Y0.afterHookedMethod(:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1214)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6598)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

2021-04-07 17:23:36.036 E/taco.scoop:crashDetectorService(11354-11354): java.lang.NoSuchMethodError: tk.wasdennnoch.scoop.ScoopApplication#xposedActive()#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at tk.wasdennnoch.scoop.XposedHook.handleLoadPackage(XposedHook.java:97)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at Y0.afterHookedMethod(:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1214)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6598)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by TacoTheDank** [comment]
@srccrow I figured as much. Are you able to use the app normally by granting root permission?

**Comment by srccrow** [comment]
> @srccrow I figured as much. Are you able to use the app normally by granting root permission?

I got stacktrace allowing root in Magisk while I was testing Lawnchair 10 Alpha 8, so yes.

**Comment by TacoTheDank** [comment]
Removed all support for Xposed as of https://github.com/TacoTheDank/Scoop/commit/a5f9b103cb2b35385592b897b35d3cc3c4e334ae

**Comment by TacoTheDank** [comment]
See https://github.com/TacoTheDank/Scoop/issues/8

**Comment by rodrigoswz** [comment]
Now that Xposed support has been re-added, 

I have the same question: any recommended settings for LSposed?

I enabled this but it doesn't seem to have any effect.
