### ISSUE TITLE
Scoop sometimes crashes when capturing traceback

### ISSUE THREAD

**Issue by jrabinow** [TacoTheDank/Scoop#50]
An app crashed while I was using it. Almost immediately I got a scoop notification, but it was a scoop crash, not a crash for the app I was using.

Given the timing, I'm assuming scoop crashed when trying to capture a traceback for the other app.

This has happened twice in the last 6h, I switched from the old xposed repo version to the fdroid app just yesterday. Speaking of which, many thanks for maintaining scoop, I was glad to see someone had adopted it.

```
java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018)
	at java.util.ArrayList.subList(ArrayList.java:1008)
	at taco.scoop.core.service.detector.CrashDetector.reportCrash(CrashDetector.kt:64)
	at taco.scoop.core.service.detector.CrashDetector.access$reportCrash(CrashDetector.kt:11)
	at taco.scoop.core.service.detector.CrashDetector$readThread$1.run(CrashDetector.kt:29)
 ```

**Comment by TacoTheDank** [comment]
🤔 Interesting, I haven't seen anyone experience something like this before...

> I was glad to see someone had adopted it.

You are most welcome! I had been using it for about two years before I decided to upgrade it as it was looking shabby :)

**Comment by TacoTheDank** [comment]
@jrabinow What Xposed system are you using? Are you still using the old Xposed, or have you updated to something like EdExposed, LSPosed, or something like that? Or, are you not using Xposed and simply relying on the root permission instead?

**Comment by jrabinow** [comment]
I'm on EdXposed but I haven't rebooted to activate the module yet, so right now things should be working in root-only mode. I'm running android 10

**Comment by jrabinow** [comment]
I rebooted and have been using the xposed module since 2 days after this issue was created. I just got the same crash twice in a row

**Comment by mjain234** [comment]
I also faced a similar issue https://drive.google.com/file/d/1YFmIaXJOZ8y-C1J4SxWAfDCA8lXQEFiW/view , whenever I am trying to open scoop settings, the app gets crashed and also when i try to see the logs of scoop getting crashed

**Comment by TacoTheDank** [comment]
@mjain234 I can't see the video, it's in your Drive's trash. 😉

**Comment by mjain234** [comment]
Cam i send it via email, if you r ok with it?😄

**Comment by TacoTheDank** [comment]
> Cam i send it via email, if you r ok with it?😄

I mean sure, but I would prefer if it were posted here so I can more easily keep track of the issue.

**Comment by mjain234** [comment]
> > Cam i send it via email, if you r ok with it?😄
> 
> I mean sure, but I would prefer if it were posted here so I can more easily keep track of the issue. You should be able to embed the video in the comment.

Sorry for commenting late, was busy for a month😅
Check this out:
This is the crash url of Scoop
https://bin.kv2.dev/~629d8953410e7c32e669e148

Also captured when scoop crashes
https://user-images.githubusercontent.com/70900505/172097920-90285b2c-a4f1-4e60-aa6a-d0902f773548.mp4

**Comment by TacoTheDank** [comment]
@mjain234 Hmm, this sounds like #45. How many crashes do you have saved? I'm looking at the scrollbar on the side here and it's very small, which implies you have a large amount of crashes. ![image](https://user-images.githubusercontent.com/32376686/172179441-95b0b8f5-5061-4a51-9573-af2ee3d40d5d.png)

**Comment by Quantenzitrone** [comment]
i think i just had the same problem
some saved stacktrace seemed to crash scoop every time i do anything other than being in the crash log overview, so
- when i click on any stacktrace to view it (and copy it)
- when i go to the settings
- when i leave the app

I don't know which stacktrace it was, and i wouldn't be able to send it to you anyway, because scoop wouldn't let me view the traces.
Anyway, I cleared all saved traces, and now it seems to work again.

My phone is a SHIFT6m with a custom ungoogled ROM by the manufacturer with Magisk Root.

**Comment by TacoTheDank** [comment]
@Quantenzitrone That sounds like #45.

**Comment by Quantenzitrone** [comment]
yeah thats sounds more like it
i probably had a large number of crashes too

**Comment by xa4hf8** [comment]
@jrabinow 
> _**...where scoop crashes while collecting its own stack trace...
...an infinite crash loop - could this scenario happen?**_

[I made Scoop crash](https://github.com/TacoTheDank/Scoop/issues/91) and there was no loop - it simply recorded the stack trace and quit
