### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by rajarshikhatua100** [TacoTheDank/Scoop#53]
FATAL EXCEPTION: main
Process: taco.scoop, PID: 21468
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class androidx.appcompat.widget.Toolbar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/main_cab_stub. Make sure other views do not use the same id.
	at android.view.View.onRestoreInstanceState(View.java:22284)
	at android.view.View.dispatchRestoreInstanceState(View.java:22256)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4826)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4826)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4826)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4826)
	at android.view.View.restoreHierarchyState(View.java:22234)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2272)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1768)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1721)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1376)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4076)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by TacoTheDank** [comment]
I'm aware of this. This will be tackled with the rewrite (which will not use the CAB library).

Also, looking at your history, I would advise that you create better issue titles. "Bug" is not very helpful.

Thank you.
