### ISSUE TITLE
Transaction Too Large exception

### ISSUE THREAD

**Issue by ZenerDeveloper** [TacoTheDank/Scoop#54]
Currently, when I open the app and either a) tap an app or b) go to settings, the app crashes. After some old school log digging I found they both have an error similar to this:
<details> <summary> Crash log </summary>
FATAL EXCEPTION: main
Process: taco.scoop, PID: 29905
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 655484 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.os.TransactionTooLargeException: data parcel size 655484 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:635)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1358)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
	... 9 more
</details>

This particular one is from entering the settings screen, while the parcel size differs by a bit when going to a crash screen. Both screens load temporarily before the app crashes, long enough to get into an actual crash report, but the app still crashes from there.
If it is any help, I have an app with 136 crashes and another with 33 crashes with some more with less than 10. Removing the worst app fixes the issue, so it seems to be related to the number of crashes loaded on the main page.

**Comment by TacoTheDank** [comment]
Duplicate of #45

But the crash log does help.

This happens when you have too many crashes saved (always clear up the old ones!). It becomes too much for the app to carry.

However, I definitely should make sure that the app doesn't crash lol.
