### ISSUE TITLE
Crash of `com.google.android.webview.canary` isn't recorded by Scoop.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [TacoTheDank/Scoop#86]
#### Error

Despite the undermentioned command:

```sh
#!/usr/bin/env sh
adb shell am start -n 'com.google.android.webview.canary' # https://stackoverflow.com/revisions/4567928/2#:~:text=adb%20shell%20am%20start%20%2Dn%20com.package.name/com.package.name.ActivityName
```

...causing the undermentioned crash:

<blockQuote>

```YAML
Exception occurred while executing 'start':
java.lang.IllegalArgumentException: Bad component name: com.google.android.webview.canary
        at android.content.Intent.parseCommandArgs(Intent.java:8458)
        at com.android.server.am.ActivityManagerShellCommand.makeIntent(ActivityManagerShellCommand.java:477)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:601)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:233)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9798)
        at android.os.Binder.shellCommand(Binder.java:1068)
        at android.os.Binder.onTransact(Binder.java:888)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5267)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2743)
        at android.os.Binder.execTransactInternal(Binder.java:1344)
        at android.os.Binder.execTransact(Binder.java:1275)
```

</blockQuote>

...Scoop doesn't record it:

> ![image](https://github.com/user-attachments/assets/60e00cbc-0762-4563-a843-27bcbc78f312)

#### Environment

As undermentioned, in [the URI](https://issues.chromium.org/issues/366123452#comment1:~:text=Android%20device%20name:,signatures:%5Be47393c5%5D%2C%20past%20signatures:%5B%5D%7D):

<blockQuote>

#### Android device name

[`cpe:/h:fairphone:fairphone_5`](https://en.wikipedia.org/w/index.php?title=Fairphone_5&oldid=1223364482)

#### Android OS version

1. ```sh
   #!/usr/bin/env sh
   adb shell getprop | grep -e 'ro.build.display.id' # https://stackoverflow.com/revisions/21099766/1#:~:text=parameters%20just%20type:-,adb%20shell%20getprop,-answered%20Jan%2013%2C
   ```

1. > ```YAML
   > [ro.build.display.id]: [FP5.UT27.B.059.20240809]
   > ```

#### Android System WebView version

1. ```sh
   #!/usr/bin/env sh
   adb shell dumpsys package 'com.google.android.webview.canary' | grep -e 'version' # https://stackoverflow.com/revisions/11943078/5#:~:text=adb%20shell%20dumpsys%20package%20my.package%20%7C%20grep%20versionName
   ```

1. > ```ini
   >     versionCode=671300033 minSdk=29 targetSdk=35
   >     versionName=130.0.6713.0
   >       com.google.android.trichromelibrary.canary version:671300033
   >     signatures=PackageSignatures{7b1856 version:3, signatures:[66320e2f], past signatures:[]}
   > ```

#### Applications (from `play.google.com`)

1. [`com.google.android.webview.canary`](https://play.google.com/store/apps/details?id=com.google.android.webview.canary&hl=en_GB)
1. [`com.discord`](https://play.google.com/store/apps/details?id=com.discord&hl=en_GB)
1. [`com.spotify.music&`](https://play.google.com/store/apps/details?id=com.spotify.music&hl=en_GB)

#### Application version

1. ```sh
   #!/usr/bin/env sh
   adb shell dumpsys package 'com.discord' | grep -e 'version' # https://stackoverflow.com/revisions/11943078/5#:~:text=adb%20shell%20dumpsys%20package%20my.package%20%7C%20grep%20versionName
   ```

1. > ```ini
   >     versionCode=247116 minSdk=24 targetSdk=34
   >     versionName=247.16 - Beta
   >     signatures=PackageSignatures{16c1bc3 version:4, signatures:[3c9ee69f], past signatures:[]}
   > ```

1. ```sh
   #!/usr/bin/env sh
   adb shell dumpsys package 'com.spotify.music' | grep -e 'version' # https://stackoverflow.com/revisions/11943078/5#:~:text=adb%20shell%20dumpsys%20package%20my.package%20%7C%20grep%20versionName
   ```

1. > ```ini
   >     versionCode=119016358 minSdk=21 targetSdk=34
   >     versionName=8.9.76.426
   >     signatures=PackageSignatures{4a035f4 version:4, signatures:[e47393c5], past signatures:[]}
   > ```

</blockQuote>

#### Verification

I've confirmed that Scoop remains able to record (other) crashes, because I can reproducibly cause the undermentioned:

<blockQuote>

```YAML
FATAL EXCEPTION: main
Process: com.twitter.android, PID: 31316
java.lang.UnsupportedOperationException: Editing b is not supported
	at d5k.invoke(Twttr:78)
	at wc5.d(Twttr:21)
	at androidx.recyclerview.widget.e0$a.d(Twttr:56)
	at oi$a.onInitializeAccessibilityNodeInfo(Twttr:254)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:8907)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:8868)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:31666)
	at android.view.View.createAccessibilityNodeInfo(View.java:8851)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1526)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1315)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:405)
	at android.view.AccessibilityInteractionController.-$$Nest$mfindAccessibilityNodeInfoByAccessibilityIdUiThread(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1719)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
```

</blockQuote>

...in [X, V10.58.0](https://www.apkmirror.com/apk/x-corp/twitter/twitter-10-58-0-release-0-release/x-previously-twitter-10-58-0-release-0-android-apk-download/#file).

#### Importance

This was problematic for me because it made diagnosing [`issues.chromium.org/issues/366123452#comment1`](https://issues.chromium.org/issues/366123452#comment1:~:text=Chrome%20WebView%20Canary%20crashes%20on%20the%20FP5.) significantly more difficult.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TacoTheDank/Scoop/issues/86#issue-2522767072

Turns out that that was because I didn't enter an activity, so I don't know whether it should have recorded it. I'll file a new bug that actually makes use of a crash log.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TacoTheDank/Scoop/issues/86#issuecomment-2352867509

I've filed https://github.com/TacoTheDank/Scoop/issues/87#issue-2528432914.
